import { readFileSync } from "node:fs";
import { chromium } from "playwright";
const env = Object.fromEntries(readFileSync(".env.local","utf8").split("\n").map(l=>l.match(/^([A-Z0-9_]+)=(.*)$/)).filter(Boolean).map(m=>[m[1],m[2].replace(/^["']|["']$/g,"")]));
const B = process.env.B ?? "http://localhost:3939", OUT = process.env.OUT;
const b = await chromium.launch({ args:["--no-sandbox"] });
const c = await b.newContext({ viewport:{width:1280,height:900} });
const p = await c.newPage();
p.on("pageerror", e => console.log("PAGEERR", e.message));
await p.goto(B+"/masuk"); await p.fill("#email", env.SEED_ADMIN_EMAIL); await p.fill("#password", env.SEED_ADMIN_PASSWORD);
await Promise.all([p.waitForURL("**/pakhuis"), p.click('button[type="submit"]')]);
await p.goto(B+"/admin/kiriminaja", { waitUntil: "networkidle" });
await p.click('button:has-text("Uji API key")'); await p.waitForTimeout(2500);
console.log("auth:", await p.locator("text=/Authorized|Gagal|belum/").first().textContent().catch(()=>"-"));
await p.click('button:has-text("Cek ongkir")'); await p.waitForTimeout(3000);
const n = await p.locator('button:text-is("Pilih")').count(); console.log("layanan:", n);
await p.locator('button:text-is("Pilih")').first().click();
await p.click('button:has-text("Buat paket")'); await p.waitForTimeout(4000);
console.log("buat:", await p.locator("text=/Order ID|wajib|tidak/").first().textContent().catch(()=>"-"));
await p.screenshot({ path: OUT+"/uji-kurir.png", fullPage: true });
await b.close();
